# It should be ndk root directory(which contains jni directory.)
LOCAL_PATH := $(call my-dir)/..
S:=..

ifndef MY_LIBS_ROOT
  MY_LIBS_ROOT := ../..
endif

include $(CLEAR_VARS)
LOCAL_MODULE := crypto
LOCAL_CFLAGS += -I.. \
	-I../include \
	-I../include/compat \
	-I../crypto/asn1 \
	-I../crypto/bn \
	-I../crypto/evp \
	-I../crypto/modes \
	-I../crypto \

LOCAL_SRC_FILES := \
	$S/ts/ts_asn1.c \
	$S/ts/ts_req_utils.c \
	$S/ts/ts_rsp_sign.c \
	$S/ts/ts_conf.c \
	$S/ts/ts_rsp_print.c \
	$S/ts/ts_req_print.c \
	$S/ts/ts_err.c \
	$S/ts/ts_rsp_utils.c \
	$S/ts/ts_rsp_verify.c \
	$S/ts/ts_verify_ctx.c \
	$S/ts/ts_lib.c \
	$S/dsa/dsa_ossl.c \
	$S/dsa/dsa_sign.c \
	$S/dsa/dsa_gen.c \
	$S/dsa/dsa_meth.c \
	$S/dsa/dsa_lib.c \
	$S/dsa/dsa_depr.c \
	$S/dsa/dsa_prn.c \
	$S/dsa/dsa_err.c \
	$S/dsa/dsa_pmeth.c \
	$S/dsa/dsa_vrf.c \
	$S/dsa/dsa_ameth.c \
	$S/dsa/dsa_key.c \
	$S/dsa/dsa_asn1.c \
	$S/chacha/chacha.c \
	$S/ecdsa/ecs_vrf.c \
	$S/ecdsa/ecs_sign.c \
	$S/ecdsa/ecs_ossl.c \
	$S/ecdsa/ecs_err.c \
	$S/ecdsa/ecs_asn1.c \
	$S/ecdsa/ecs_lib.c \
	$S/rc2/rc2_skey.c \
	$S/rc2/rc2ofb64.c \
	$S/rc2/rc2cfb64.c \
	$S/rc2/rc2_ecb.c \
	$S/rc2/rc2_cbc.c \
	$S/whrlpool/wp_block.c \
	$S/whrlpool/wp_dgst.c \
	$S/x509v3/v3_ia5.c \
	$S/x509v3/v3_pcons.c \
	$S/x509v3/pcy_map.c \
	$S/x509v3/v3_pci.c \
	$S/x509v3/v3_pcia.c \
	$S/x509v3/v3_ocsp.c \
	$S/x509v3/v3_skey.c \
	$S/x509v3/v3_purp.c \
	$S/x509v3/v3_sxnet.c \
	$S/x509v3/v3_pku.c \
	$S/x509v3/v3_lib.c \
	$S/x509v3/v3_crld.c \
	$S/x509v3/v3_enum.c \
	$S/x509v3/v3_alt.c \
	$S/x509v3/v3_bcons.c \
	$S/x509v3/pcy_data.c \
	$S/x509v3/pcy_cache.c \
	$S/x509v3/v3_int.c \
	$S/x509v3/v3_genn.c \
	$S/x509v3/v3_akeya.c \
	$S/x509v3/v3_bitst.c \
	$S/x509v3/v3_utl.c \
	$S/x509v3/v3_prn.c \
	$S/x509v3/pcy_tree.c \
	$S/x509v3/v3_ncons.c \
	$S/x509v3/v3_info.c \
	$S/x509v3/v3_cpols.c \
	$S/x509v3/v3err.c \
	$S/x509v3/v3_extku.c \
	$S/x509v3/v3_akey.c \
	$S/x509v3/pcy_node.c \
	$S/x509v3/v3_conf.c \
	$S/x509v3/pcy_lib.c \
	$S/x509v3/v3_pmaps.c \
	$S/bf/bf_skey.c \
	$S/bf/bf_enc.c \
	$S/bf/bf_ecb.c \
	$S/bf/bf_cfb64.c \
	$S/bf/bf_ofb64.c \
	$S/gost/gostr341001_ameth.c \
	$S/gost/gostr341001_pmeth.c \
	$S/gost/gost_err.c \
	$S/gost/gostr341001.c \
	$S/gost/gost_asn1.c \
	$S/gost/gost89imit_ameth.c \
	$S/gost/gostr341194.c \
	$S/gost/gostr341001_key.c \
	$S/gost/gost89imit_pmeth.c \
	$S/gost/gost89_params.c \
	$S/gost/streebog.c \
	$S/gost/gost2814789.c \
	$S/gost/gost89_keywrap.c \
	$S/gost/gostr341001_params.c \
	$S/idea/i_cfb64.c \
	$S/idea/i_skey.c \
	$S/idea/i_cbc.c \
	$S/idea/i_ofb64.c \
	$S/idea/i_ecb.c \
	$S/buffer/buffer.c \
	$S/buffer/buf_str.c \
	$S/buffer/buf_err.c \
	$S/o_time.c \
	$S/cpt_err.c \
	$S/cryptlib.c \
	$S/modes/xts128.c \
	$S/modes/ccm128.c \
	$S/modes/gcm128.c \
	$S/modes/ofb128.c \
	$S/modes/cts128.c \
	$S/modes/cbc128.c \
	$S/modes/ctr128.c \
	$S/modes/cfb128.c \
	$S/rra_portable/inet_aton.c \
	$S/rra_portable/getnameinfo.c \
	$S/rra_portable/snprintf.c \
	$S/rra_portable/inet_ntoa.c \
	$S/rra_portable/getaddrinfo.c \
	$S/rra_portable/inet_ntop.c \
	$S/rra_portable/inet_pton.c \
	$S/md4/md4_dgst.c \
	$S/md4/md4_one.c \
	$S/dso/dso_lib.c \
	$S/dso/dso_dlfcn.c \
	$S/dso/dso_openssl.c \
	$S/dso/dso_null.c \
	$S/dso/dso_err.c \
	$S/hkdf/hkdf.c \
	$S/stack/stack.c \
	$S/txt_db/txt_db.c \
	$S/bn/bn_mpi.c \
	$S/bn/bn_asm.c \
	$S/bn/bn_prime.c \
	$S/bn/bn_const.c \
	$S/bn/bn_depr.c \
	$S/bn/bn_nist.c \
	$S/bn/bn_gf2m.c \
	$S/bn/bn_sqr.c \
	$S/bn/bn_rand.c \
	$S/bn/bn_err.c \
	$S/bn/bn_ctx.c \
	$S/bn/bn_lib.c \
	$S/bn/bn_mont.c \
	$S/bn/bn_mod.c \
	$S/bn/bn_mul.c \
	$S/bn/bn_recp.c \
	$S/bn/bn_kron.c \
	$S/bn/bn_gcd.c \
	$S/bn/bn_exp2.c \
	$S/bn/bn_x931p.c \
	$S/bn/bn_div.c \
	$S/bn/bn_shift.c \
	$S/bn/bn_add.c \
	$S/bn/bn_word.c \
	$S/bn/bn_exp.c \
	$S/bn/bn_sqrt.c \
	$S/bn/bn_print.c \
	$S/bn/bn_blind.c \
	$S/dh/dh_depr.c \
	$S/dh/dh_key.c \
	$S/dh/dh_check.c \
	$S/dh/dh_pmeth.c \
	$S/dh/dh_gen.c \
	$S/dh/dh_prn.c \
	$S/dh/dh_asn1.c \
	$S/dh/dh_err.c \
	$S/dh/dh_ameth.c \
	$S/dh/dh_lib.c \
	$S/ripemd/rmd_one.c \
	$S/ripemd/rmd_dgst.c \
	$S/conf/conf_sap.c \
	$S/conf/conf_def.c \
	$S/conf/conf_lib.c \
	$S/conf/conf_mall.c \
	$S/conf/conf_mod.c \
	$S/conf/conf_err.c \
	$S/conf/conf_api.c \
	$S/ecdh/ech_lib.c \
	$S/ecdh/ech_err.c \
	$S/ecdh/ech_key.c \
	$S/mem_clr.c \
	$S/err/err_prn.c \
	$S/err/err.c \
	$S/err/err_all.c \
	$S/pkcs7/pk7_attr.c \
	$S/pkcs7/pkcs7err.c \
	$S/pkcs7/pk7_asn1.c \
	$S/pkcs7/pk7_doit.c \
	$S/pkcs7/pk7_smime.c \
	$S/pkcs7/pk7_mime.c \
	$S/pkcs7/bio_pk7.c \
	$S/pkcs7/pk7_lib.c \
	$S/comp/comp_err.c \
	$S/comp/comp_lib.c \
	$S/comp/c_rle.c \
	$S/comp/c_zlib.c \
	$S/lhash/lh_stats.c \
	$S/lhash/lhash.c \
	$S/malloc-wrapper.c \
	$S/hmac/hmac.c \
	$S/hmac/hm_ameth.c \
	$S/hmac/hm_pmeth.c \
	$S/rand/rand_lib.c \
	$S/rand/randfile.c \
	$S/rand/rand_err.c \
	$S/ocsp/ocsp_prn.c \
	$S/ocsp/ocsp_err.c \
	$S/ocsp/ocsp_ext.c \
	$S/ocsp/ocsp_vfy.c \
	$S/ocsp/ocsp_ht.c \
	$S/ocsp/ocsp_cl.c \
	$S/ocsp/ocsp_lib.c \
	$S/ocsp/ocsp_srv.c \
	$S/ocsp/ocsp_asn.c \
	$S/x509/x509spki.c \
	$S/x509/x509_v3.c \
	$S/x509/by_dir.c \
	$S/x509/x509_r2x.c \
	$S/x509/x509rset.c \
	$S/x509/x509_lu.c \
	$S/x509/x509_err.c \
	$S/x509/x509_d2.c \
	$S/x509/x509_def.c \
	$S/x509/x509_vfy.c \
	$S/x509/x_all.c \
	$S/x509/by_mem.c \
	$S/x509/x509_att.c \
	$S/x509/x509_ext.c \
	$S/x509/x509_set.c \
	$S/x509/x509_vpm.c \
	$S/x509/x509_txt.c \
	$S/x509/x509name.c \
	$S/x509/by_file.c \
	$S/x509/x509_req.c \
	$S/x509/x509type.c \
	$S/x509/x509cset.c \
	$S/x509/x509_obj.c \
	$S/x509/x509_trs.c \
	$S/x509/x509_cmp.c \
	$S/ui/ui_err.c \
	$S/ui/ui_openssl_win.c \
	$S/ui/ui_openssl.c \
	$S/ui/ui_util.c \
	$S/ui/ui_lib.c \
	$S/crypto_init.c \
	$S/o_init.c \
	$S/cversion.c \
	$S/poly1305/poly1305.c \
	$S/ex_data.c \
	$S/rc4/rc4_skey.c \
	$S/rc4/rc4_enc.c \
	$S/bio/bss_dgram.c \
	$S/bio/bss_mem.c \
	$S/bio/b_print.c \
	$S/bio/bss_null.c \
	$S/bio/bss_log.c \
	$S/bio/bio_cb.c \
	$S/bio/bio_lib.c \
	$S/bio/bio_err.c \
	$S/bio/b_dump.c \
	$S/bio/b_win.c \
	$S/bio/bss_conn.c \
	$S/bio/b_posix.c \
	$S/bio/bf_buff.c \
	$S/bio/bf_null.c \
	$S/bio/bf_nbio.c \
	$S/bio/bss_acpt.c \
	$S/bio/b_sock.c \
	$S/bio/bss_sock.c \
	$S/bio/bss_file.c \
	$S/bio/bss_bio.c \
	$S/bio/bss_fd.c \
	$S/bio/bio_meth.c \
	$S/sha/sha256.c \
	$S/sha/sha1dgst.c \
	$S/sha/sha512.c \
	$S/sha/sha1_one.c \
	$S/des/set_key.c \
	$S/des/pcbc_enc.c \
	$S/des/ofb_enc.c \
	$S/des/fcrypt.c \
	$S/des/cbc_cksm.c \
	$S/des/qud_cksm.c \
	$S/des/ecb_enc.c \
	$S/des/fcrypt_b.c \
	$S/des/rand_key.c \
	$S/des/ofb64ede.c \
	$S/des/enc_read.c \
	$S/des/cbc_enc.c \
	$S/des/xcbc_enc.c \
	$S/des/ecb3_enc.c \
	$S/des/enc_writ.c \
	$S/des/cfb64ede.c \
	$S/des/des_enc.c \
	$S/des/ede_cbcm_enc.c \
	$S/des/cfb_enc.c \
	$S/des/ofb64enc.c \
	$S/des/str2key.c \
	$S/des/cfb64enc.c \
	$S/camellia/cmll_ofb.c \
	$S/camellia/cmll_ctr.c \
	$S/camellia/cmll_cbc.c \
	$S/camellia/camellia.c \
	$S/camellia/cmll_ecb.c \
	$S/camellia/cmll_misc.c \
	$S/camellia/cmll_cfb.c \
	$S/rsa/rsa_lib.c \
	$S/rsa/rsa_chk.c \
	$S/rsa/rsa_depr.c \
	$S/rsa/rsa_eay.c \
	$S/rsa/rsa_crpt.c \
	$S/rsa/rsa_err.c \
	$S/rsa/rsa_oaep.c \
	$S/rsa/rsa_x931.c \
	$S/rsa/rsa_pss.c \
	$S/rsa/rsa_saos.c \
	$S/rsa/rsa_pk1.c \
	$S/rsa/rsa_meth.c \
	$S/rsa/rsa_asn1.c \
	$S/rsa/rsa_gen.c \
	$S/rsa/rsa_sign.c \
	$S/rsa/rsa_prn.c \
	$S/rsa/rsa_ameth.c \
	$S/rsa/rsa_pmeth.c \
	$S/rsa/rsa_none.c \
	$S/compat/getentropy_win.c \
	$S/compat/posix_win.c \
	$S/compat/arc4random_uniform.c \
	$S/compat/strcasecmp.c \
	$S/compat/getpagesize.c \
	$S/compat/arc4random.c \
	$S/compat/freezero.c \
	$S/compat/strndup.c \
	$S/compat/bsd-asprintf.c \
	$S/compat/strlcpy.c \
	$S/compat/timegm.c \
	$S/compat/explicit_bzero_win.c \
	$S/compat/getentropy_linux.c \
	$S/compat/strnlen.c \
	$S/compat/recallocarray.c \
	$S/compat/reallocarray.c \
	$S/compat/timingsafe_bcmp.c \
	$S/compat/strsep.c \
	$S/compat/explicit_bzero.c \
	$S/compat/timingsafe_memcmp.c \
	$S/compat/strlcat.c \
	$S/cmac/cm_pmeth.c \
	$S/cmac/cmac.c \
	$S/cmac/cm_ameth.c \
	$S/asn1/x_pubkey.c \
	$S/asn1/a_time_tm.c \
	$S/asn1/asn1_gen.c \
	$S/asn1/evp_asn1.c \
	$S/asn1/bio_ndef.c \
	$S/asn1/t_crl.c \
	$S/asn1/tasn_prn.c \
	$S/asn1/x_x509a.c \
	$S/asn1/x_sig.c \
	$S/asn1/asn1_lib.c \
	$S/asn1/a_mbstr.c \
	$S/asn1/t_spki.c \
	$S/asn1/a_digest.c \
	$S/asn1/asn_moid.c \
	$S/asn1/bio_asn1.c \
	$S/asn1/a_strnid.c \
	$S/asn1/i2d_pr.c \
	$S/asn1/ameth_lib.c \
	$S/asn1/tasn_typ.c \
	$S/asn1/nsseq.c \
	$S/asn1/a_i2d_fp.c \
	$S/asn1/t_pkey.c \
	$S/asn1/x_attrib.c \
	$S/asn1/a_set.c \
	$S/asn1/tasn_fre.c \
	$S/asn1/x_bignum.c \
	$S/asn1/x_info.c \
	$S/asn1/a_dup.c \
	$S/asn1/a_d2i_fp.c \
	$S/asn1/a_verify.c \
	$S/asn1/p8_pkey.c \
	$S/asn1/tasn_utl.c \
	$S/asn1/a_sign.c \
	$S/asn1/a_object.c \
	$S/asn1/a_bytes.c \
	$S/asn1/x_nx509.c \
	$S/asn1/x_exten.c \
	$S/asn1/x_val.c \
	$S/asn1/t_req.c \
	$S/asn1/n_pkey.c \
	$S/asn1/x_long.c \
	$S/asn1/a_print.c \
	$S/asn1/a_time.c \
	$S/asn1/d2i_pu.c \
	$S/asn1/asn1_par.c \
	$S/asn1/x_spki.c \
	$S/asn1/x_pkey.c \
	$S/asn1/a_enum.c \
	$S/asn1/x_req.c \
	$S/asn1/i2d_pu.c \
	$S/asn1/a_octet.c \
	$S/asn1/tasn_dec.c \
	$S/asn1/tasn_enc.c \
	$S/asn1/t_x509a.c \
	$S/asn1/tasn_new.c \
	$S/asn1/p5_pbev2.c \
	$S/asn1/a_strex.c \
	$S/asn1/t_x509.c \
	$S/asn1/x_crl.c \
	$S/asn1/asn_mime.c \
	$S/asn1/a_bitstr.c \
	$S/asn1/asn1_err.c \
	$S/asn1/x_x509.c \
	$S/asn1/a_type.c \
	$S/asn1/x_algor.c \
	$S/asn1/d2i_pr.c \
	$S/asn1/p5_pbe.c \
	$S/asn1/a_int.c \
	$S/asn1/asn_pack.c \
	$S/asn1/x_name.c \
	$S/asn1/a_utf8.c \
	$S/asn1/a_bool.c \
	$S/asn1/f_int.c \
	$S/asn1/f_enum.c \
	$S/asn1/f_string.c \
	$S/asn1/t_bitst.c \
	$S/mem_dbg.c \
	$S/curve25519/curve25519.c \
	$S/curve25519/curve25519-generic.c \
	$S/md5/md5_one.c \
	$S/md5/md5_dgst.c \
	$S/pem/pem_pkey.c \
	$S/pem/pem_lib.c \
	$S/pem/pem_xaux.c \
	$S/pem/pem_pk8.c \
	$S/pem/pem_info.c \
	$S/pem/pem_seal.c \
	$S/pem/pem_all.c \
	$S/pem/pem_sign.c \
	$S/pem/pem_oth.c \
	$S/pem/pvkfmt.c \
	$S/pem/pem_err.c \
	$S/pem/pem_x509.c \
	$S/evp/e_aes.c \
	$S/evp/m_ripemd.c \
	$S/evp/e_chacha.c \
	$S/evp/p_enc.c \
	$S/evp/m_md5.c \
	$S/evp/pmeth_gn.c \
	$S/evp/bio_md.c \
	$S/evp/p_lib.c \
	$S/evp/evp_pkey.c \
	$S/evp/e_rc2.c \
	$S/evp/p_open.c \
	$S/evp/m_ecdsa.c \
	$S/evp/e_idea.c \
	$S/evp/e_bf.c \
	$S/evp/p_dec.c \
	$S/evp/evp_err.c \
	$S/evp/m_sigver.c \
	$S/evp/p_seal.c \
	$S/evp/m_dss1.c \
	$S/evp/bio_b64.c \
	$S/evp/p5_crpt2.c \
	$S/evp/bio_enc.c \
	$S/evp/p_sign.c \
	$S/evp/e_des.c \
	$S/evp/e_cast.c \
	$S/evp/pmeth_lib.c \
	$S/evp/m_dss.c \
	$S/evp/m_md5_sha1.c \
	$S/evp/e_chacha20poly1305.c \
	$S/evp/evp_pbe.c \
	$S/evp/encode.c \
	$S/evp/m_md4.c \
	$S/evp/c_all.c \
	$S/evp/names.c \
	$S/evp/p5_crpt.c \
	$S/evp/m_gostr341194.c \
	$S/evp/evp_aead.c \
	$S/evp/e_old.c \
	$S/evp/evp_key.c \
	$S/evp/evp_enc.c \
	$S/evp/e_gost2814789.c \
	$S/evp/e_rc4_hmac_md5.c \
	$S/evp/e_aes_cbc_hmac_sha1.c \
	$S/evp/e_des3.c \
	$S/evp/m_sha1.c \
	$S/evp/e_rc4.c \
	$S/evp/m_null.c \
	$S/evp/e_null.c \
	$S/evp/pmeth_fn.c \
	$S/evp/m_wp.c \
	$S/evp/p_verify.c \
	$S/evp/digest.c \
	$S/evp/m_gost2814789.c \
	$S/evp/m_streebog.c \
	$S/evp/evp_lib.c \
	$S/evp/e_xcbc_d.c \
	$S/evp/e_camellia.c \
	$S/engine/eng_cnf.c \
	$S/engine/tb_dsa.c \
	$S/engine/eng_fat.c \
	$S/engine/tb_digest.c \
	$S/engine/eng_ctrl.c \
	$S/engine/tb_pkmeth.c \
	$S/engine/tb_asnmth.c \
	$S/engine/tb_cipher.c \
	$S/engine/eng_list.c \
	$S/engine/tb_store.c \
	$S/engine/eng_openssl.c \
	$S/engine/eng_all.c \
	$S/engine/eng_err.c \
	$S/engine/eng_lib.c \
	$S/engine/eng_table.c \
	$S/engine/tb_ecdsa.c \
	$S/engine/tb_ecdh.c \
	$S/engine/eng_dyn.c \
	$S/engine/eng_init.c \
	$S/engine/tb_dh.c \
	$S/engine/eng_pkey.c \
	$S/engine/tb_rsa.c \
	$S/engine/tb_rand.c \
	$S/objects/obj_xref.c \
	$S/objects/obj_dat.c \
	$S/objects/obj_err.c \
	$S/objects/obj_lib.c \
	$S/objects/o_names.c \
	$S/o_str.c \
	$S/pkcs12/p12_p8d.c \
	$S/pkcs12/p12_attr.c \
	$S/pkcs12/p12_asn.c \
	$S/pkcs12/p12_mutl.c \
	$S/pkcs12/p12_crt.c \
	$S/pkcs12/p12_init.c \
	$S/pkcs12/p12_npas.c \
	$S/pkcs12/p12_key.c \
	$S/pkcs12/p12_add.c \
	$S/pkcs12/p12_p8e.c \
	$S/pkcs12/p12_utl.c \
	$S/pkcs12/p12_kiss.c \
	$S/pkcs12/p12_crpt.c \
	$S/pkcs12/p12_decr.c \
	$S/pkcs12/pk12err.c \
	$S/aes/aes_ige.c \
	$S/aes/aes_ofb.c \
	$S/aes/aes_cbc.c \
	$S/aes/aes_cfb.c \
	$S/aes/aes_wrap.c \
	$S/aes/aes_ecb.c \
	$S/aes/aes_core.c \
	$S/aes/aes_ctr.c \
	$S/aes/aes_misc.c \
	$S/cast/c_ecb.c \
	$S/cast/c_enc.c \
	$S/cast/c_ofb64.c \
	$S/cast/c_skey.c \
	$S/cast/c_cfb64.c \
	$S/ec/ec_ameth.c \
	$S/ec/ec2_smpl.c \
	$S/ec/ec_oct.c \
	$S/ec/ec_err.c \
	$S/ec/ec_cvt.c \
	$S/ec/ecp_smpl.c \
	$S/ec/ec_lib.c \
	$S/ec/ec_mult.c \
	$S/ec/eck_prn.c \
	$S/ec/ec_check.c \
	$S/ec/ec_key.c \
	$S/ec/ecp_mont.c \
	$S/ec/ec2_oct.c \
	$S/ec/ec_pmeth.c \
	$S/ec/ec2_mult.c \
	$S/ec/ec_curve.c \
	$S/ec/ec_asn1.c \
	$S/ec/ec_print.c \
	$S/ec/ecp_nist.c \
	$S/ec/ecp_oct.c \
	$S/dll_main.c \

include $(BUILD_SHARED_LIBRARY)

